import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]),
    CLERK_SECRET_KEY: z.string().min(1).optional(),
    CLERK_FRONTEND_API_URL: z.string().url().optional(),
    CLERK_JWT_ISSUER_DOMAIN: z.string().url().optional(),
    LIVEKIT_API_KEY: z.string().min(1).optional(),
    LIVEKIT_API_SECRET: z.string().min(1).optional(),
    LIVEKIT_AGENT_NAME: z.string().min(1).optional(),
    LIVEKIT_AGENT_STT_MODEL: z.string().min(1).optional(),
    LIVEKIT_AGENT_LLM_MODEL: z.string().min(1).optional(),
    LIVEKIT_AGENT_TTS_MODEL: z.string().min(1).optional(),
    LIVEKIT_AGENT_CHILD_TTS_MODEL: z.string().min(1).optional(),
    LIVEKIT_AGENT_WRAP_TTS_MODEL: z.string().min(1).optional(),
    LIVEKIT_AGENT_INSTRUCTIONS: z.string().min(1).optional(),
    LIVEKIT_AGENT_CHILD_INSTRUCTIONS: z.string().min(1).optional(),
    LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS: z.string().min(1).optional(),
    LIVEKIT_AGENT_LOG_LEVEL: z.string().min(1).optional(),
    LIVEKIT_WEBHOOK_API_KEY: z.string().min(1).optional(),
    LIVEKIT_WEBHOOK_API_SECRET: z.string().min(1).optional(),
    LIVEKIT_RECORDING_ENABLED: z.enum(["0", "1"]).optional(),
    LIVEKIT_RECORDING_AUDIO_ONLY: z.enum(["0", "1"]).optional(),
    LIVEKIT_RECORDING_TEMPLATE_URL: z.string().min(1).optional(),
    LIVEKIT_RECORDING_STORAGE_BUCKET: z.string().min(1).optional(),
    LIVEKIT_RECORDING_STORAGE_REGION: z.string().min(1).optional(),
    LIVEKIT_RECORDING_STORAGE_ACCESS_KEY: z.string().min(1).optional(),
    LIVEKIT_RECORDING_STORAGE_SECRET_KEY: z.string().min(1).optional(),
    KYMA_ENABLE_DEMO_INVITE: z.enum(["0", "1"]).optional(),
    KYMA_REVIEW_CHAT_MODEL: z.string().min(1).optional(),
    KYMA_PROCESSING_WRITE_KEY: z.string().min(1).optional(),
    INNGEST_APP_ID: z.string().min(1).optional(),
    PLAYWRIGHT_BASE_URL: z.string().url().optional(),
    PLAYWRIGHT_SKIP_WEBSERVER: z.string().min(1).optional(),
    CI: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1).optional(),
    NEXT_PUBLIC_LIVEKIT_URL: z.string().min(1).optional(),
    NEXT_PUBLIC_CONVEX_URL: z.string().url().optional(),
    NEXT_PUBLIC_ENABLE_DEV_TRACE: z.enum(["0", "1"]).optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    CLERK_FRONTEND_API_URL: process.env.CLERK_FRONTEND_API_URL,
    CLERK_JWT_ISSUER_DOMAIN: process.env.CLERK_JWT_ISSUER_DOMAIN,
    LIVEKIT_API_KEY: process.env.LIVEKIT_API_KEY,
    LIVEKIT_API_SECRET: process.env.LIVEKIT_API_SECRET,
    LIVEKIT_AGENT_NAME: process.env.LIVEKIT_AGENT_NAME,
    LIVEKIT_AGENT_STT_MODEL: process.env.LIVEKIT_AGENT_STT_MODEL,
    LIVEKIT_AGENT_LLM_MODEL: process.env.LIVEKIT_AGENT_LLM_MODEL,
    LIVEKIT_AGENT_TTS_MODEL: process.env.LIVEKIT_AGENT_TTS_MODEL,
    LIVEKIT_AGENT_CHILD_TTS_MODEL: process.env.LIVEKIT_AGENT_CHILD_TTS_MODEL,
    LIVEKIT_AGENT_WRAP_TTS_MODEL: process.env.LIVEKIT_AGENT_WRAP_TTS_MODEL,
    LIVEKIT_AGENT_INSTRUCTIONS: process.env.LIVEKIT_AGENT_INSTRUCTIONS,
    LIVEKIT_AGENT_CHILD_INSTRUCTIONS: process.env.LIVEKIT_AGENT_CHILD_INSTRUCTIONS,
    LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS: process.env.LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS,
    LIVEKIT_AGENT_LOG_LEVEL: process.env.LIVEKIT_AGENT_LOG_LEVEL,
    LIVEKIT_WEBHOOK_API_KEY: process.env.LIVEKIT_WEBHOOK_API_KEY,
    LIVEKIT_WEBHOOK_API_SECRET: process.env.LIVEKIT_WEBHOOK_API_SECRET,
    LIVEKIT_RECORDING_ENABLED: process.env.LIVEKIT_RECORDING_ENABLED,
    LIVEKIT_RECORDING_AUDIO_ONLY: process.env.LIVEKIT_RECORDING_AUDIO_ONLY,
    LIVEKIT_RECORDING_TEMPLATE_URL: process.env.LIVEKIT_RECORDING_TEMPLATE_URL,
    LIVEKIT_RECORDING_STORAGE_BUCKET: process.env.LIVEKIT_RECORDING_STORAGE_BUCKET,
    LIVEKIT_RECORDING_STORAGE_REGION: process.env.LIVEKIT_RECORDING_STORAGE_REGION,
    LIVEKIT_RECORDING_STORAGE_ACCESS_KEY:
      process.env.LIVEKIT_RECORDING_STORAGE_ACCESS_KEY,
    LIVEKIT_RECORDING_STORAGE_SECRET_KEY:
      process.env.LIVEKIT_RECORDING_STORAGE_SECRET_KEY,
    KYMA_ENABLE_DEMO_INVITE: process.env.KYMA_ENABLE_DEMO_INVITE,
    KYMA_REVIEW_CHAT_MODEL: process.env.KYMA_REVIEW_CHAT_MODEL,
    KYMA_PROCESSING_WRITE_KEY: process.env.KYMA_PROCESSING_WRITE_KEY,
    INNGEST_APP_ID: process.env.INNGEST_APP_ID,
    PLAYWRIGHT_BASE_URL: process.env.PLAYWRIGHT_BASE_URL,
    PLAYWRIGHT_SKIP_WEBSERVER: process.env.PLAYWRIGHT_SKIP_WEBSERVER,
    CI: process.env.CI,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_LIVEKIT_URL: process.env.NEXT_PUBLIC_LIVEKIT_URL,
    NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
    NEXT_PUBLIC_ENABLE_DEV_TRACE: process.env.NEXT_PUBLIC_ENABLE_DEV_TRACE,
  },
  emptyStringAsUndefined: true,
});
