import { env } from '@/lib/env'

export function getLivekitEnv() {
  return {
    NEXT_PUBLIC_LIVEKIT_URL: env.NEXT_PUBLIC_LIVEKIT_URL,
    LIVEKIT_API_KEY: env.LIVEKIT_API_KEY,
    LIVEKIT_API_SECRET: env.LIVEKIT_API_SECRET,
    LIVEKIT_AGENT_NAME: env.LIVEKIT_AGENT_NAME,
    LIVEKIT_WEBHOOK_API_KEY: env.LIVEKIT_WEBHOOK_API_KEY,
    LIVEKIT_WEBHOOK_API_SECRET: env.LIVEKIT_WEBHOOK_API_SECRET,
    LIVEKIT_RECORDING_ENABLED: env.LIVEKIT_RECORDING_ENABLED,
    LIVEKIT_RECORDING_AUDIO_ONLY: env.LIVEKIT_RECORDING_AUDIO_ONLY,
    LIVEKIT_RECORDING_TEMPLATE_URL: env.LIVEKIT_RECORDING_TEMPLATE_URL,
    LIVEKIT_RECORDING_STORAGE_BUCKET: env.LIVEKIT_RECORDING_STORAGE_BUCKET,
    LIVEKIT_RECORDING_STORAGE_REGION: env.LIVEKIT_RECORDING_STORAGE_REGION,
    LIVEKIT_RECORDING_STORAGE_ACCESS_KEY:
      env.LIVEKIT_RECORDING_STORAGE_ACCESS_KEY,
    LIVEKIT_RECORDING_STORAGE_SECRET_KEY:
      env.LIVEKIT_RECORDING_STORAGE_SECRET_KEY,
  }
}

export function hasLivekitServerCredentials() {
  const livekitEnv = getLivekitEnv()

  return Boolean(
    livekitEnv.NEXT_PUBLIC_LIVEKIT_URL &&
    livekitEnv.LIVEKIT_API_KEY &&
    livekitEnv.LIVEKIT_API_SECRET
  )
}

export function getLivekitWebhookSigningCredentials() {
  const livekitEnv = getLivekitEnv()

  return {
    apiKey: livekitEnv.LIVEKIT_WEBHOOK_API_KEY ?? livekitEnv.LIVEKIT_API_KEY,
    apiSecret:
      livekitEnv.LIVEKIT_WEBHOOK_API_SECRET ?? livekitEnv.LIVEKIT_API_SECRET,
  }
}
