import { runtimeEnvConfig } from '@/lib/env/runtime'

export const agentEnv = {
  LIVEKIT_AGENT_NAME: runtimeEnvConfig.LIVEKIT_AGENT_NAME,
  LIVEKIT_AGENT_STT_MODEL: runtimeEnvConfig.LIVEKIT_AGENT_STT_MODEL,
  LIVEKIT_AGENT_LLM_MODEL: runtimeEnvConfig.LIVEKIT_AGENT_LLM_MODEL,
  LIVEKIT_AGENT_TTS_MODEL: runtimeEnvConfig.LIVEKIT_AGENT_TTS_MODEL,
  LIVEKIT_AGENT_CHILD_TTS_MODEL: runtimeEnvConfig.LIVEKIT_AGENT_CHILD_TTS_MODEL,
  LIVEKIT_AGENT_WRAP_TTS_MODEL: runtimeEnvConfig.LIVEKIT_AGENT_WRAP_TTS_MODEL,
  LIVEKIT_AGENT_INSTRUCTIONS: runtimeEnvConfig.LIVEKIT_AGENT_INSTRUCTIONS,
  LIVEKIT_AGENT_CHILD_INSTRUCTIONS:
    runtimeEnvConfig.LIVEKIT_AGENT_CHILD_INSTRUCTIONS,
  LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS:
    runtimeEnvConfig.LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS,
  LIVEKIT_AGENT_LOG_LEVEL: runtimeEnvConfig.LIVEKIT_AGENT_LOG_LEVEL,
  LIVEKIT_API_KEY: runtimeEnvConfig.LIVEKIT_API_KEY,
  LIVEKIT_API_SECRET: runtimeEnvConfig.LIVEKIT_API_SECRET,
  NEXT_PUBLIC_LIVEKIT_URL: runtimeEnvConfig.NEXT_PUBLIC_LIVEKIT_URL,
}
