import { runtimeEnvConfig } from '@/lib/env/runtime'

export const convexEnv = {
  NODE_ENV: runtimeEnvConfig.NODE_ENV,
  CLERK_SECRET_KEY: runtimeEnvConfig.CLERK_SECRET_KEY,
  CLERK_FRONTEND_API_URL: runtimeEnvConfig.CLERK_FRONTEND_API_URL,
  CLERK_JWT_ISSUER_DOMAIN: runtimeEnvConfig.CLERK_JWT_ISSUER_DOMAIN,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
    runtimeEnvConfig.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  KYMA_ENABLE_DEMO_INVITE: runtimeEnvConfig.KYMA_ENABLE_DEMO_INVITE,
  KYMA_PROCESSING_WRITE_KEY: runtimeEnvConfig.KYMA_PROCESSING_WRITE_KEY,
}
