import { env } from '@/lib/env/schema'

export const publicEnv = {
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  NEXT_PUBLIC_LIVEKIT_URL: env.NEXT_PUBLIC_LIVEKIT_URL,
  NEXT_PUBLIC_CONVEX_URL: env.NEXT_PUBLIC_CONVEX_URL,
  NEXT_PUBLIC_ENABLE_DEV_TRACE: env.NEXT_PUBLIC_ENABLE_DEV_TRACE,
}
