import 'server-only'
import { env } from '@/lib/env/schema'

export const serverEnv = {
  NODE_ENV: env.NODE_ENV,
  CLERK_SECRET_KEY: env.CLERK_SECRET_KEY,
  CLERK_FRONTEND_API_URL: env.CLERK_FRONTEND_API_URL,
  CLERK_JWT_ISSUER_DOMAIN: env.CLERK_JWT_ISSUER_DOMAIN,
  LIVEKIT_API_KEY: env.LIVEKIT_API_KEY,
  LIVEKIT_API_SECRET: env.LIVEKIT_API_SECRET,
  LIVEKIT_AGENT_NAME: env.LIVEKIT_AGENT_NAME,
  LIVEKIT_AGENT_STT_MODEL: env.LIVEKIT_AGENT_STT_MODEL,
  LIVEKIT_AGENT_LLM_MODEL: env.LIVEKIT_AGENT_LLM_MODEL,
  LIVEKIT_AGENT_TTS_MODEL: env.LIVEKIT_AGENT_TTS_MODEL,
  LIVEKIT_AGENT_CHILD_TTS_MODEL: env.LIVEKIT_AGENT_CHILD_TTS_MODEL,
  LIVEKIT_AGENT_WRAP_TTS_MODEL: env.LIVEKIT_AGENT_WRAP_TTS_MODEL,
  LIVEKIT_AGENT_INSTRUCTIONS: env.LIVEKIT_AGENT_INSTRUCTIONS,
  LIVEKIT_AGENT_CHILD_INSTRUCTIONS: env.LIVEKIT_AGENT_CHILD_INSTRUCTIONS,
  LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS: env.LIVEKIT_AGENT_WRAP_UP_INSTRUCTIONS,
  LIVEKIT_AGENT_LOG_LEVEL: env.LIVEKIT_AGENT_LOG_LEVEL,
  LIVEKIT_WEBHOOK_API_KEY: env.LIVEKIT_WEBHOOK_API_KEY,
  LIVEKIT_WEBHOOK_API_SECRET: env.LIVEKIT_WEBHOOK_API_SECRET,
  LIVEKIT_RECORDING_ENABLED: env.LIVEKIT_RECORDING_ENABLED,
  LIVEKIT_RECORDING_AUDIO_ONLY: env.LIVEKIT_RECORDING_AUDIO_ONLY,
  LIVEKIT_RECORDING_TEMPLATE_URL: env.LIVEKIT_RECORDING_TEMPLATE_URL,
  LIVEKIT_RECORDING_STORAGE_BUCKET: env.LIVEKIT_RECORDING_STORAGE_BUCKET,
  LIVEKIT_RECORDING_STORAGE_REGION: env.LIVEKIT_RECORDING_STORAGE_REGION,
  LIVEKIT_RECORDING_STORAGE_ACCESS_KEY:
    env.LIVEKIT_RECORDING_STORAGE_ACCESS_KEY,
  LIVEKIT_RECORDING_STORAGE_SECRET_KEY:
    env.LIVEKIT_RECORDING_STORAGE_SECRET_KEY,
  KYMA_ENABLE_DEMO_INVITE: env.KYMA_ENABLE_DEMO_INVITE,
  KYMA_REVIEW_CHAT_MODEL: env.KYMA_REVIEW_CHAT_MODEL,
  KYMA_PROCESSING_WRITE_KEY: env.KYMA_PROCESSING_WRITE_KEY,
  INNGEST_APP_ID: env.INNGEST_APP_ID,
  PLAYWRIGHT_BASE_URL: env.PLAYWRIGHT_BASE_URL,
  PLAYWRIGHT_SKIP_WEBSERVER: env.PLAYWRIGHT_SKIP_WEBSERVER,
  CI: env.CI,
}
